### ISSUE TITLE
Where is the data saved

### ISSUE THREAD

**Issue by ugintl** [mablue/Specialized-Procurement-and-Sales-Management-System-for-East-Azarbaijan-Gas-Company#15]
What backend it is using? Where is the data saved? Is it possible to use mysql?

**Comment by mablue** [comment]
> What backend it is using? Where is the data saved? Is it possible to use mysql?

Django, sqlite database file, yes

**Comment by ugintl** [comment]
How can I use mysql?

**Comment by mablue** [comment]
Django framework have good intro for that in his website
Just check the version of django and django doc you want to read
